### ISSUE TITLE
Api Server use method - callback being called several times

### ISSUE THREAD

**Issue by TiagoVenceslau** [PrivateSky/apihub#2]
With the changes shown in the meeting in this [fork](https://github.com/TiagoVenceslau/apihub/tree/request_logging) and with the following entry in the server's server.json file:
```
  "logging": {
    "enabled": true,
  },
```
Example:
```
...
  "port": 8080,
  "storage": "../apihub-root",
  "logging": {
    "enabled": true,
  },
  "preventRateLimit": true,
  "enableRequestLogger": true,
...
```
 for a basic request we get the output bellow, where:
* `x/y` means its running the middleware x of y registered middlewares;
* `Request handled in...`  means the callback has been called by the middleware x;
* any other output is cause by the acting middlewares (for instance, the logging middleware is the 3rd)

Should the callback be called so many times? I would expect only once, for the matching middleware (in this case it's 49: the '*' URL pattern)

```
0/52
- Request handled in 0 milliseconds
1/52
2/52
- Request handled in 1 milliseconds
[GET] /assets/images/cube.png
3/52
- Request handled in 3 milliseconds
4/52
5/52
6/52
7/52
8/52
9/52
10/52
11/52
12/52
13/52
14/52
15/52
16/52
17/52
18/52
19/52
20/52
21/52
22/52
23/52
24/52
25/52
26/52
27/52
28/52
29/52
30/52
31/52
32/52
33/52
34/52
35/52
36/52
37/52
38/52
39/52
40/52
41/52
42/52
43/52
44/52
45/52
46/52
47/52
48/52
- Request handled in 49 milliseconds
49/52
- Request handled in 52 milliseconds```

**Comment by joaoluis-pdm** [comment]
Just to inform duplication of the issue at https://github.com/PharmaLedger-IMI/epi-workspace/issues/61
(@salboaie  requested that the issue was moved to epi-workspace, but we cannot close it here).

**Comment by asaccool** [comment]
Hi Tiago,

I would like to propose a different approach in order to implement the middleware capable to measure and log how much time it takes for a request to be resolved.

I propose to create a middleware called "**StopWatchLogger**" and to write some code like in the followings:
```
function StopWatchLogger(server) {

	//the purpose of startStopWatch middleware will be to register the starting time
	//and to overwrite the end function of the response object in order to register the end time.
	function startStopWatch(request, response, next) {

		//we save the starting time
		let startTime = new Date().getTime();

		//at this point we save the response.end function reference for later use
		let end = response.end;

		//set response.end function to be ours
		response.end = function (...args) {
			//call the native response.end function with all the args received
			end(...args);
			//we save the ending time
			let endTime = new Date().getTime();
			console.log(`Resolving request ${request.url} took ${endTime - startTime}ms.`);
		}
        //allow the execution of the next middlewares until request is resolved
		next();
	}

    //we register a middleware for all the paths/urls
	server.use(`*`, startStopWatch);
}

module.exports = StopWatchLogger;
```
After the middleware is created we need to ensure that is the first one that will be registered into apihub in order not to lose any requests.

Also the override of the response.end function needs a little bit more elaboration in order to handle the arguments properly if we need to count also the time it take from the call of end function until the response stream is done. As in [nodejs http docs](https://nodejs.org/api/http.html#http_response_end_data_encoding_callback) end function can receive a callback argument that will be called when the response stream will end.

**Motivation**: When a middleware is registered in apihub will be added into a list of middlewares. When apihub receives a request extracts a short list from the list of middlwares the ones that match the request.url. The short list of middlewares is iterated one by one. If a middleware takes the responsability to call the response.end function than no other middleware will be called. If the middleware logic doesn't provide a final response it calls the next argument function and signals that the next middleware needs to be called.

**Comment by joaoluis-pdm** [comment]
JS noob question:

The solution @asaccool gave (although it looks good) appears to fail in the line where we call end(...args):
```
...
[GET] /fgt-mah-wallet/loader/
Caught event type [uncaughtException]. Shutting down... uncaughtException TypeError: Cannot read property 'finished' of undefined
    at end (_http_outgoing.js:747:12)
    at ServerResponse.res.end (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:4071:9) <--- this was my own local modification - line where end(...args) is called.
    at ReadStream.onend (_stream_readable.js:683:10)
    at Object.onceWrapper (events.js:420:28)
    at ReadStream.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Exit caught on spawned file /export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js 


```
I do not really understand why it fails, as it seems a "clean" end() extension. The function end() appears to come from the Stream prototype.

**Comment by asaccool** [comment]
@joaoluis-pdm i didn't run the code that i gave as exemple. At this point is seems there is an issue with the value of "this".
I think that if you change the line where we call the end function 
```
end(...args);
```
with
```
end.call(response, ...args);
```
should work ok.

**Comment by joaoluis-pdm** [comment]
@asaccool your tip works well.

**Comment by joaoluis-pdm** [comment]
Just for warming up my JS I have an implementation proposal in
https://github.com/joaoluis-pdm/apihub/commit/2a3dcf10184f4cb6eb3cd0b1c9552ae866d5a787

It is opinionated:
* has a timestamp prefix with resolution up to milisecond. (milisecond resolution is not enough in some other projects, where we have to link request/response with  uuid - for example - but if in this case might be enough).
* makes no sense to keep both loggers (the original, and this one) turned on.
* in no way this answers the problem reported by  @TiagoV-PDMFC in this issue. (Although there seems to be no multiple response.end() calls - I don't really understands who calls the end() method.).

Let me know if you want a pull request.

**Comment by asaccool** [comment]
> * in no way this answers the problem reported by  @TiagoV-PDMFC in this issue. (Although there seems to be no multiple response.end() calls - I don't really understands who calls the end() method.).

@joaoluis-pdm for my point of view the implementation done by @TiagoVenceslau doesn't show a bug, I can say that there is a misunderstanding of the code.

The server.use function allows us to register functions that will be registered in the middleware array of functions that will be iterated once a new request arrives on the server. 

As the code shows 
```
this.use = function use(url, callback) {
...
        if (arguments.length >= 2) {
// here we call the middlware.use to register for a specific url a handler function called cb
            middleware.use(url, cb);
        } else if (arguments.length === 1) {
            callback = url;
//here we call the middleware.use to register a handler function for all of the requests
            middleware.use(cb);
        }
    };
```
Even next functions are wrappers over middleware.use function and just playing with the args for that function.
```
this.get = function getReq(reqUrl, reqResolver) {
        middleware.use("GET", reqUrl, reqResolver);
    };

    this.post = function postReq(reqUrl, reqResolver) {
        middleware.use("POST", reqUrl, reqResolver);
    };

    this.put = function putReq(reqUrl, reqResolver) {
        middleware.use("PUT", reqUrl, reqResolver);
    };

    this.delete = function deleteReq(reqUrl, reqResolver) {
        middleware.use("DELETE", reqUrl, reqResolver);
    };

    this.options = function optionsReq(reqUrl, reqResolver) {
        middleware.use("OPTIONS", reqUrl, reqResolver);
    };
```

Let's consider that we have a server (a small stub for a messaging service) that knows to respond in the next cases:
```
OPTIONS *
PUT /create-channel/:channelName
POST /send-message/:channelName
GET /read-messages/:channelName
```
In our server implementation we will register the following handlers:
```
server.options("*", optionsHandler);
server.put("/create-channel/:channelName", createChannelHandler);
server.post("/send-message/:channelName", sendMessageHandler);
server.get("/read-messages/:channelName", readMessagesHandler);
//we always need a fallback in case there is any handler function capable to resolve the request
server.use("*", NotFoundHandler);
```
which will translate in a array of middlewares as followes
```
registeredMiddlewares = [
{url: "*", "method":"OPTIONS", "handler": optionsHandler},
{url: "/create-channel/:channelName", "method":"PUT", "handler": createChannelHandler},
{url: "/send-message/:channelName", "method":"POST", "handler": sendMessageHandler},
{url: "/read-messages/:channelName", "method":"GET", "handler": readMessagesHandler},
{url: "*", "handler": NotFoundHandler}
]
```
Each handler that is register needs the have the following signature:
```
function name(request, response, next){
//... business logic implementation for the handler
}
```
Once our server receives for example a request **PUT /create-channel/support** a list of middlewares will be "extracted" like [createChannelHandler, NotFoundHandler]. In this case only this two middlewares are selected because of the matching process based on method and url. Then an iteration over this array is started with the calling of createChannelHandler. If in that handler the conditions to execute the request are not satisfied and the **next** argument of the handler gets called the process will continue with the call the next handler registered and matched, in our case NotFoundHandler. 

Now if we look at @TiagoVenceslau 's implementation we can see that the log message " - Request handled in " will be displayed right before each handler function call will be made and not at the end of the request handling process. And thus why I proposed a different approach to resolve the initial problem.
